services:
  pereval-app:
    container_name: pereval
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./Pereval:/Pereval
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"